[package]
name = "ewwii_plugin_api"
version = "0.1.1"
authors = ["byson94 <byson94wastaken@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"
description = "The full ewwii plugin API shared library for building plugins"
repository = "https://github.com/byson94/ewwii"
homepage = "https://github.com/byson94/ewwii"

[dependencies]
rhai = { workspace = true }