[book]
authors = ["byson94"]
language = "en"
multilingual = false
src = "src"
title = "Ewii documentation"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/byson94/ewwii/tree/master/docs"
site-url = "/"