[book]
authors = ["byson94"]
language = "en"
multilingual = false
src = "src"
title = "Ewwii documentation"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/Ewwii-sh/ewwii"
site-url = "/"
additional-js = ["js/home_button.js"]