[book]
authors = ["elkowar"]
language = "en"
multilingual = false
src = "src"
title = "eww documentation"


[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/byson94/ewwii/tree/master/docs"