[book]
authors = ["byson94"]
language = "en"
multilingual = false
src = "src"
title = "Ewwii documentation"

[output.html]
default-theme = "latte"
preferred-dark-theme = "macchiato"
git-repository-url = "https://github.com/Ewwii-sh/ewwii"
additional-js = ["js/home_button.js"]
additional-css = ["./theme/catppuccin.css"]