name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel gtk4 gtk4-layer-shell pkgconf git

      - uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Load rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check with default features
        run: cargo check

      - name: Run tests
        run: cargo test

      - name: Check x11 only
        run: cargo check --no-default-features --features=x11

      - name: Check wayland only
        run: cargo check --no-default-features --features=wayland

      - name: Check no-backend
        run: cargo check --no-default-features 
