name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Install GTK4 dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y \
                libgtk-4-dev \
                libgtk-layer-shell-dev \
                pkg-config \
                build-essential

            - uses: actions/checkout@v4

            - name: Setup rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy,rustfmt

            - name: Load rust cache
              uses: Swatinem/rust-cache@v2

            - name: Setup problem matchers
              uses: r7kamura/rust-problem-matchers@v1

            - name: Check formatting
              run: cargo fmt -- --check
            - name: Check with default features
              run: cargo check

            - name: Run tests
              run: cargo test

            - name: Check x11 only
              run: cargo check --no-default-features --features=x11
            - name: Check wayland only
              run: cargo check --no-default-features --features=wayland
            - name: Check no-backend
              run: cargo check --no-default-features
