name: Build and deploy Github pages

on:
    push:
        branches:
            - main
        paths:
            - "docs/**"
            - ".github/workflows/**"

permissions:
    contents: write

jobs:
    build:
        name: Build mdBook
        runs-on: ubuntu-latest

        steps:
            # Checkout code
            - name: Checkout repository
              uses: actions/checkout@v4

            # Cache apt package lists
            - name: Cache apt-get package lists
              uses: actions/cache@v3
              with:
                  path: |
                      /var/cache/apt/archives
                      /var/lib/apt/lists
                  key: ${{ runner.os }}-apt-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-apt-

            # Install necessary dependencies for glib-sys and gobject-sys
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    pkg-config \
                    libcairo2-dev \
                    libglib2.0-dev \
                    libgirepository1.0-dev \
                    libpango1.0-dev \
                    libatk1.0-dev \
                    libgtk-3-dev

            # Cache Rust toolchain
            - name: Cache Rust toolchain
              uses: actions/cache@v4
              with:
                  path: ~/.cargo
                  key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-rust-

            # Install Rust
            - name: Install Rust
              run: |
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
                  source $HOME/.cargo/env

            # Cache Cargo registry and git directory
            - name: Cache Cargo registry and git
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            # Generate module docs
            - name: Generate module docs
              run: cargo run --release -p generate-rhai-docs

            # Build mdBook
            - name: Build mdBook page
              uses: peaceiris/actions-mdbook@v1
              with:
                  mdbook-version: "0.4.52"

            - name: Run mdBook build
              run: mdbook build docs

            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/book/
